model:
  target_name: "gpt2"

activation:
  layer_idx: 5
  max_length: 64
  normalize: true

dataset:
  num_samples: 20000
  output_dir: "datasets/activation_buffer"

training:
  batch_size: 16
  lr: 0.0001
  epochs: 10
  hidden_dim: 2048
  save_dir: "checkpoints/ar"

tracking:
  use_wandb: true
  project: "TinyNLA"
  run_name: "gpt2_layer3_meanpool"
  
device: "cpu"